import { ModuleDefinition, ModuleNature, ViewMode, FieldType, FieldLocation, BlockType, FieldNature, LogicOperator } from '../types';

const GRID_MATERIALS_BLOCK = {
  id: 'grid_materials',
  titles: { fa: 'مواد اولیه', en: 'Materials' },
  type: BlockType.GRID_TABLE,
  order: 1,
  gridConfig: {
    categories: [
      { value: 'leather', label: 'چرم', specBlockId: 'leatherSpec' },
      { value: 'lining', label: 'آستر', specBlockId: 'liningSpec' },
      { value: 'accessory', label: 'خرجکار', specBlockId: 'kharjkarSpec' },
      { value: 'fitting', label: 'یراق', specBlockId: 'yaraghSpec' },
    ],
  },
};

const MATERIAL_CATEGORY_OPTIONS = [
  { label: 'چرم', value: 'leather' },
  { label: 'آستر', value: 'lining' },
  { label: 'خرجکار', value: 'accessory' },
  { label: 'یراق', value: 'fitting' },
];

const PRODUCT_SPEC_BLOCKS = [
  {
    id: 'leatherSpec',
    titles: { fa: 'ویژگی های چرم', en: 'Leather Specs' },
    type: BlockType.FIELD_GROUP,
    order: 6,
    visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'leather' },
  },
  {
    id: 'liningSpec',
    titles: { fa: 'ویژگی های آستر', en: 'Lining Specs' },
    type: BlockType.FIELD_GROUP,
    order: 7,
    visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'lining' },
  },
  {
    id: 'kharjkarSpec',
    titles: { fa: 'ویژگی های خرجکار', en: 'Accessory Specs' },
    type: BlockType.FIELD_GROUP,
    order: 8,
    visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'accessory' },
  },
  {
    id: 'yaraghSpec',
    titles: { fa: 'ویژگی های یراق', en: 'Fitting Specs' },
    type: BlockType.FIELD_GROUP,
    order: 9,
    visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'fitting' },
  },
];

export const productionBomModule: ModuleDefinition = {
  id: 'production_boms',
  titles: { fa: 'شناسنامه‌های تولید (BOM)', en: 'Production BOMs' },
  nature: ModuleNature.PRODUCTION,
  supportedViewModes: [ViewMode.LIST],
  defaultViewMode: ViewMode.LIST,
  fields: [
    { key: 'image_url', labels: { fa: 'تصویر', en: 'Image' }, type: FieldType.IMAGE, location: FieldLocation.HEADER, order: 0, nature: FieldNature.PREDEFINED, isTableColumn: true },
    { key: 'name', labels: { fa: 'عنوان مدل', en: 'Name' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1, isKey: true, validation: { required: true }, isTableColumn: true },
    { key: 'system_code', labels: { fa: 'کد سیستمی', en: 'Sys Code' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 2, readonly: true, isTableColumn: true },
    { key: 'status', labels: { fa: 'وضعیت', en: 'Status' }, type: FieldType.STATUS, location: FieldLocation.HEADER, order: 4, options: [{ label: 'فعال', value: 'active', color: 'green' }, { label: 'بایگانی', value: 'archived', color: 'gray' }], defaultValue: 'active' },
    { 
      key: 'product_category', 
      labels: { fa: 'دسته بندی محصول', en: 'Product Category' }, 
      type: FieldType.SELECT, 
      location: FieldLocation.HEADER, 
      order: 2.5, 
      dynamicOptionsCategory: 'product_categories',
      nature: FieldNature.STANDARD, 
      validation: { required: false },
      isTableColumn: true,
    },  
    { 
      key: 'production_stages', 
      labels: { fa: 'مراحل تولید', en: 'Stages' }, 
      type: FieldType.PROGRESS_STAGES,
      location: FieldLocation.BLOCK, 
      order: 9,  
      isTableColumn: true,
      nature: FieldNature.STANDARD 
    },
    {
      key: 'production_stages_draft',
      labels: { fa: 'پیش‌نویس مراحل تولید', en: 'Draft Stages' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      order: 19,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'grid_materials',
      labels: { fa: 'مواد اولیه', en: 'Materials' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      order: 20,
      nature: FieldNature.STANDARD,
    },
  ],
  blocks: [
    GRID_MATERIALS_BLOCK
  ],
  relatedTabs: [],
  table: 'production_boms',
  actionButtons: [
    { id: 'create_production_order', label: 'ایجاد سفارش تولید', placement: 'header', variant: 'primary' }
  ]
};

export const productionOrderModule: ModuleDefinition = {
  id: 'production_orders',
  titles: { fa: 'سفارشات تولید', en: 'Production Orders' },
  nature: ModuleNature.PRODUCTION,
  supportedViewModes: [ViewMode.LIST],
  defaultViewMode: ViewMode.LIST,
  fields: [
    { key: 'image_url', labels: { fa: 'تصویر', en: 'Image' }, type: FieldType.IMAGE, location: FieldLocation.HEADER, order: 0, nature: FieldNature.PREDEFINED, isTableColumn: true },
    { key: 'name', labels: { fa: 'عنوان سفارش', en: 'Name' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 1, isKey: true, validation: { required: true }, isTableColumn: true },
    { key: 'system_code', labels: { fa: 'کد سیستمی', en: 'Code' }, type: FieldType.TEXT, location: FieldLocation.HEADER, order: 2, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'bom_id', labels: { fa: 'انتخاب شناسنامه (BOM)', en: 'Select BOM' }, type: FieldType.RELATION, location: FieldLocation.HEADER, order: 2, relationConfig: { targetModule: 'production_boms', targetField: 'name' } },
    {
      key: 'production_group_order_id',
      labels: { fa: 'سفارش گروهی مرتبط', en: 'Related Group Order' },
      type: FieldType.RELATION,
      location: FieldLocation.HEADER,
      order: 2.4,
      relationConfig: { targetModule: 'production_group_orders', targetField: 'name' },
      nature: FieldNature.STANDARD,
      validation: { required: false },
      isTableColumn: true,
    },
    { 
      key: 'product_category', 
      labels: { fa: 'دسته بندی محصول', en: 'Product Category' }, 
      type: FieldType.STATUS, 
      location: FieldLocation.HEADER, 
      order: 2.5, 
      dynamicOptionsCategory: 'product_categories',
      nature: FieldNature.STANDARD, 
      validation: { required: false },
    },
    {
      key: 'category',
      labels: { fa: 'دسته بندی مواد اولیه', en: 'Material Category' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 2.55,
      options: MATERIAL_CATEGORY_OPTIONS,
      nature: FieldNature.STANDARD,
      validation: { required: false },
    },
    {
      key: 'color',
      labels: { fa: 'رنگ', en: 'Color' },
      type: FieldType.SELECT,
      location: FieldLocation.HEADER,
      order: 2.6,
      dynamicOptionsCategory: 'general_color',
      nature: FieldNature.STANDARD,
      validation: { required: false },
    },
    {
      key: 'auto_name_enabled',
      labels: { fa: 'نامگذاری خودکار', en: 'Auto Name' },
      type: FieldType.CHECKBOX,
      location: FieldLocation.HEADER,
      order: 2.7,
      defaultValue: true,
      nature: FieldNature.STANDARD,
    },
    { key: 'quantity', labels: { fa: 'تعداد تولید', en: 'Production Qty' }, type: FieldType.STOCK, location: FieldLocation.HEADER, order: 3, validation: { required: true }, readonly: true, nature: FieldNature.SYSTEM },
    { key: 'production_cost', labels: { fa: 'جمع کل (برآورد هزینه)', en: 'Estimated Cost' }, type: FieldType.PRICE, location: FieldLocation.HEADER, order: 3.5, readonly: true, nature: FieldNature.SYSTEM },
    { key: 'status', labels: { fa: 'وضعیت', en: 'Status' }, type: FieldType.STATUS, location: FieldLocation.HEADER, order: 4, options: [{ label: 'در انتظار', value: 'pending', color: 'orange' }, { label: 'در حال تولید', value: 'in_progress', color: 'blue' }, { label: 'تکمیل شده', value: 'completed', color: 'green' }], defaultValue: 'pending', isTableColumn: true },
    { key: 'production_started_at', labels: { fa: '\u0632\u0645\u0627\u0646 \u0634\u0631\u0648\u0639 \u062a\u0648\u0644\u06cc\u062f', en: 'Production Start Time' }, type: FieldType.DATETIME, location: FieldLocation.HEADER, order: 4.1, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'production_stopped_at', labels: { fa: '\u0632\u0645\u0627\u0646 \u062a\u0648\u0642\u0641 \u062a\u0648\u0644\u06cc\u062f', en: 'Production Stop Time' }, type: FieldType.DATETIME, location: FieldLocation.HEADER, order: 4.2, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { key: 'production_completed_at', labels: { fa: '\u0632\u0645\u0627\u0646 \u062a\u06a9\u0645\u06cc\u0644 \u062a\u0648\u0644\u06cc\u062f', en: 'Production Complete Time' }, type: FieldType.DATETIME, location: FieldLocation.HEADER, order: 4.3, readonly: true, nature: FieldNature.SYSTEM, isTableColumn: true },
    { 
      key: 'production_stages', 
      labels: { fa: 'مراحل تولید', en: 'Stages' }, 
      type: FieldType.PROGRESS_STAGES,
      location: FieldLocation.BLOCK, 
      order: 10,  
      isTableColumn: true,
      nature: FieldNature.STANDARD 
    },
    
    {
      key: 'production_stages_draft',
      labels: { fa: 'پیش‌نویس مراحل تولید', en: 'Draft Stages' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      order: 19,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'grid_materials',
      labels: { fa: 'مواد اولیه', en: 'Materials' },
      type: FieldType.JSON,
      location: FieldLocation.BLOCK,
      order: 20,
      nature: FieldNature.STANDARD,
    },
    {
      key: 'leather_type',
      labels: { fa: 'نوع چرم', en: 'Leather Type' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'leatherSpec',
      order: 20.1,
      dynamicOptionsCategory: 'leather_type',
      nature: FieldNature.STANDARD,
      logic: { visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'leather' } },
    },
    {
      key: 'leather_colors',
      labels: { fa: 'رنگ چرم', en: 'Leather Colors' },
      type: FieldType.MULTI_SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'leatherSpec',
      order: 20.2,
      dynamicOptionsCategory: 'general_color',
      nature: FieldNature.STANDARD,
      logic: { visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'leather' } },
    },
    {
      key: 'leather_finish_1',
      labels: { fa: 'صفحه چرم', en: 'Finish 1' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'leatherSpec',
      order: 20.3,
      dynamicOptionsCategory: 'leather_finish',
      nature: FieldNature.STANDARD,
      logic: { visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'leather' } },
    },
    {
      key: 'leather_effect',
      labels: { fa: 'افکت چرم', en: 'Leather Effect' },
      type: FieldType.MULTI_SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'leatherSpec',
      order: 20.4,
      dynamicOptionsCategory: 'leather_effect',
      nature: FieldNature.STANDARD,
      logic: { visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'leather' } },
    },
    {
      key: 'leather_sort',
      labels: { fa: 'سورت چرم', en: 'Leather Sort' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'leatherSpec',
      order: 20.5,
      dynamicOptionsCategory: 'leather_sort',
      nature: FieldNature.STANDARD,
      logic: { visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'leather' } },
    },
    {
      key: 'lining_material',
      labels: { fa: 'جنس آستر', en: 'Lining Material' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'liningSpec',
      order: 20.6,
      dynamicOptionsCategory: 'lining_material',
      nature: FieldNature.STANDARD,
      logic: { visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'lining' } },
    },
    {
      key: 'lining_color',
      labels: { fa: 'رنگ آستر', en: 'Lining Color' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'liningSpec',
      order: 20.7,
      dynamicOptionsCategory: 'general_color',
      nature: FieldNature.STANDARD,
      logic: { visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'lining' } },
    },
    {
      key: 'lining_width',
      labels: { fa: 'عرض آستر', en: 'Lining Width' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'liningSpec',
      order: 20.8,
      dynamicOptionsCategory: 'lining_width',
      nature: FieldNature.STANDARD,
      logic: { visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'lining' } },
    },
    {
      key: 'acc_material',
      labels: { fa: 'جنس خرجکار', en: 'Accessory Material' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'kharjkarSpec',
      order: 20.9,
      dynamicOptionsCategory: 'acc_material',
      nature: FieldNature.STANDARD,
      logic: { visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'accessory' } },
    },
    {
      key: 'fitting_type',
      labels: { fa: 'نوع یراق', en: 'Fitting Type' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'yaraghSpec',
      order: 21,
      dynamicOptionsCategory: 'fitting_type',
      nature: FieldNature.STANDARD,
      logic: { visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'fitting' } },
    },
    {
      key: 'fitting_material',
      labels: { fa: 'جنس یراق', en: 'Fitting Material' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'yaraghSpec',
      order: 21.1,
      dynamicOptionsCategory: 'fitting_material',
      nature: FieldNature.STANDARD,
      logic: { visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'fitting' } },
    },
    {
      key: 'fitting_colors',
      labels: { fa: 'رنگ یراق', en: 'Fitting Colors' },
      type: FieldType.MULTI_SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'yaraghSpec',
      order: 21.2,
      dynamicOptionsCategory: 'general_color',
      nature: FieldNature.STANDARD,
      logic: { visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'fitting' } },
    },
    {
      key: 'fitting_size',
      labels: { fa: 'سایز یراق', en: 'Fitting Size' },
      type: FieldType.SELECT,
      location: FieldLocation.BLOCK,
      blockId: 'yaraghSpec',
      order: 21.3,
      dynamicOptionsCategory: 'fitting_size',
      nature: FieldNature.STANDARD,
      logic: { visibleIf: { field: 'category', operator: LogicOperator.EQUALS, value: 'fitting' } },
    },
  ],
  blocks: [
    ...PRODUCT_SPEC_BLOCKS,
    GRID_MATERIALS_BLOCK
  ],
  
  relatedTabs: [],
  table: 'production_orders'
};

