import { lazy, Suspense, useEffect } from "react";
import { Route, Routes, Outlet } from "react-router-dom";
import { Refine, Authenticated } from "@refinedev/core";
import { notificationProvider, ErrorComponent } from "@refinedev/antd";
import { dataProvider } from "@refinedev/supabase";
import routerBindings, {
  UnsavedChangesNotifier,
  DocumentTitleHandler,
  CatchAllNavigate,
} from "@refinedev/react-router-v6";
import { Spin } from "antd";
import { authProvider } from "./authProvider";
import { supabase } from "./supabaseClient";
import { MODULES } from "./moduleRegistry";

const Layout = lazy(() => import("./components/Layout"));
const ProfilePage = lazy(() => import("./pages/ProfilePage"));
const SettingsPage = lazy(() => import("./pages/Settings/SettingsPage"));
const ModuleShow = lazy(() => import("./pages/ModuleShow"));
const Dashboard = lazy(() => import("./pages/Dashboard"));
const ProductionGroupOrdersList = lazy(() => import("./pages/ProductionGroupOrdersList"));
const ProductionGroupOrderWizard = lazy(() => import("./pages/ProductionGroupOrderWizard"));
const HRPage = lazy(() => import("./pages/HRPage"));
const FilesGalleryPage = lazy(() => import("./pages/FilesGalleryPage"));
const ModuleListRefine = lazy(() =>
  import("./pages/ModuleList_Refine").then((module) => ({ default: module.ModuleListRefine }))
);
const ModuleCreate = lazy(() =>
  import("./pages/ModuleCreate").then((module) => ({ default: module.ModuleCreate }))
);

const APP_TITLE = "مهربانو اتوماسیون";

const FullScreenLoader = () => (
  <div className="min-h-screen bg-gray-100 flex items-center justify-center">
    <Spin size="large" />
  </div>
);

function AuthenticatedApp() {
  useEffect(() => {
    const publicPaths = ["/inquiry", "/login"];

    const { data: subscription } = supabase.auth.onAuthStateChange((event) => {
      const eventName = String(event);
      const pathname = window.location.pathname;
      const isPublic = publicPaths.some((path) => pathname === path || pathname.startsWith(`${path}/`));

      if (eventName === "SIGNED_OUT" && !isPublic) {
        window.location.replace("/login");
      }
    });

    return () => {
      subscription?.subscription?.unsubscribe();
    };
  }, []);


  const resources = Object.values(MODULES).map((mod) => ({
    name: mod.id,
    list: `/${mod.id}`,
    show: `/${mod.id}/:id`,
    create: `/${mod.id}/create`,
    edit: `/${mod.id}/:id`,
    meta: {
      label: mod.titles.fa,
    },
  }));

  const getStandalonePageTitle = (pathname?: string) => {
    if (!pathname) return null;
    if (pathname === "/") return "داشبورد";
    if (pathname.startsWith("/login")) return "ورود";
    if (pathname.startsWith("/inquiry")) return "فرم استعلام";
    if (pathname.startsWith("/settings")) return "تنظیمات";
    if (pathname.startsWith("/profile")) return "پروفایل";
    if (pathname.startsWith("/hr")) return "منابع انسانی";
    if (pathname.startsWith("/gallery")) return "گالری فایل‌ها";
    return null;
  };

  const getActionLabel = (action?: string) => {
    if (action === "list") return "لیست";
    if (action === "create") return "ایجاد";
    if (action === "edit") return "ویرایش";
    if (action === "show") return "جزئیات";
    return "";
  };

  const titleHandler = ({
    resource,
    action,
    pathname,
  }: {
    resource?: any;
    action?: string;
    pathname?: string;
    autoGeneratedTitle: string;
  }) => {
    const standalone = getStandalonePageTitle(pathname);
    if (standalone) return `${standalone} | ${APP_TITLE}`;

    const resourceLabel =
      resource?.meta?.label || resource?.label || MODULES?.[resource?.name]?.titles?.fa || resource?.name || "";

    if (resourceLabel) {
      if (action === "show" || action === "edit") {
        return `${resourceLabel} | ${APP_TITLE}`;
      }
      const actionLabel = getActionLabel(action);
      return actionLabel ? `${actionLabel} ${resourceLabel} | ${APP_TITLE}` : `${resourceLabel} | ${APP_TITLE}`;
    }

    return APP_TITLE;
  };

  return (
    <Refine
      dataProvider={dataProvider(supabase)}
      authProvider={authProvider}
      notificationProvider={notificationProvider}
      routerProvider={routerBindings}
      resources={resources}
      options={{
        syncWithLocation: true,
        warnWhenUnsavedChanges: true,
      }}
    >
      <Suspense fallback={<FullScreenLoader />}>
        <Routes>
          <Route
            element={
              <Authenticated key="authenticated-inner" fallback={<CatchAllNavigate to="/login" />}>
                <Layout isDarkMode={false} toggleTheme={() => {}}>
                  <Outlet />
                </Layout>
              </Authenticated>
            }
          >
            <Route index element={<Dashboard />} />
            <Route path="/profile" element={<ProfilePage />} />
            <Route path="/production_group_orders" element={<ProductionGroupOrdersList />} />
            <Route path="/production_group_orders/create" element={<ProductionGroupOrderWizard />} />
            <Route path="/production_group_orders/:id" element={<ProductionGroupOrderWizard />} />
            <Route path="/hr" element={<HRPage />} />
            <Route path="/hr/:employeeId" element={<HRPage />} />
            <Route path="/gallery" element={<FilesGalleryPage />} />

            <Route path="/:moduleId">
              <Route index element={<ModuleListRefine />} />
              <Route path="create" element={<ModuleCreate />} />
              <Route path=":id" element={<ModuleShow />} />
              <Route path=":id/edit" element={<ModuleShow />} />
            </Route>

            <Route path="/settings" element={<SettingsPage />} />
            <Route path="*" element={<ErrorComponent />} />
          </Route>
        </Routes>
      </Suspense>

      <UnsavedChangesNotifier />
      <DocumentTitleHandler handler={titleHandler} />
    </Refine>
  );
}

export default AuthenticatedApp;
